In [46]:
import pandas as pd
import re
import numpy as np

In [72]:
# fp = r"C:\Users\Clover\Documents\GitHub\DVA_Team_173\notebooks\carina\tweets_kaggle_labelled.csv"
fp = '../../data_full/raw/twitter_data/kaggle/tweets_kaggle_labelled_with_tickers.csv'
df = pd.read_csv(fp)

# df.shape
df.head()

,id,created_at,full_text,predicted_score,stock_ticker
0,1,2020-04-09 23:59:51+00:00,@KennyDegu very very little volume. With $10T ...,-0.637271,['SPX']
1,2,2020-04-09 23:58:55+00:00,#ES_F achieved Target 2780 closing above 50% #...,0.919818,"['SPX', 'SPY']"
2,3,2020-04-09 23:58:52+00:00,RT @KimbleCharting: Silver/Gold indicator crea...,0.906212,NaN
3,4,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,-1.062240,['MSFT']
4,5,2020-04-09 23:57:59+00:00,RT @zipillinois: 3 Surprisingly Controversial ...,-1.061654,"['GILD', 'MO']"

In [73]:

# Function to extract stock tickers
def extract_tickers(text):
    tickers = re.findall(r'\$[A-Za-z]+', str(text))  # Find tickers with "$"
    tickers = [t.replace("$", "").upper() for t in tickers]  # Remove "$" and uppercase
    return tickers if tickers else None  # Return None if no tickers found

# Apply function to create new columns
df["stock_ticker"] = df["full_text"].apply(extract_tickers)
df["num_stocks"] = df["stock_ticker"].apply(lambda x: len(x) if x else 0)  # Count number of tickers

# Save the updated file (optional)
# df.to_csv("tweets_kaggle_labelled_with_tickers2.csv", index=False)

# Show sample output
# print(df[["full_text", "stock_ticker", "num_stocks"]].head())
# df.head()

In [74]:
df.head()

,id,created_at,full_text,predicted_score,stock_ticker,num_stocks
0,1,2020-04-09 23:59:51+00:00,@KennyDegu very very little volume. With $10T ...,-0.637271,[SPX],1
1,2,2020-04-09 23:58:55+00:00,#ES_F achieved Target 2780 closing above 50% #...,0.919818,"[SPX, SPY]",2
2,3,2020-04-09 23:58:52+00:00,RT @KimbleCharting: Silver/Gold indicator crea...,0.906212,None,0
3,4,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,-1.062240,[MSFT],1
4,5,2020-04-09 23:57:59+00:00,RT @zipillinois: 3 Surprisingly Controversial ...,-1.061654,"[GILD, MO]",2

In [75]:
def check_dtypes(df):
    for column in df.columns:
        dtype = df[column].dtype
        print(f"Column '{column}' has datatype: {dtype}")

# Example usage:
check_dtypes(df)

Column 'id' has datatype: int64
Column 'created_at' has datatype: object
Column 'full_text' has datatype: object
Column 'predicted_score' has datatype: float64
Column 'stock_ticker' has datatype: object
Column 'num_stocks' has datatype: int64

In [76]:
def check_nulls(df):
    for column in df.columns:
        null_count = df[column].isnull().sum()
        print(f"Column '{column}' has {null_count} null value(s).")

# Example usage:
check_nulls(df)

Column 'id' has 0 null value(s).
Column 'created_at' has 0 null value(s).
Column 'full_text' has 0 null value(s).
Column 'predicted_score' has 0 null value(s).
Column 'stock_ticker' has 198260 null value(s).
Column 'num_stocks' has 0 null value(s).

In [77]:
df_filtered = df.dropna(subset=['stock_ticker']).reset_index(drop=True)
check_dtypes(df_filtered)
print(" ")
check_nulls(df_filtered)
df_filtered.head()
df_filtered.shape

Column 'id' has datatype: int64
Column 'created_at' has datatype: object
Column 'full_text' has datatype: object
Column 'predicted_score' has datatype: float64
Column 'stock_ticker' has datatype: object
Column 'num_stocks' has datatype: int64

Column 'id' has 0 null value(s).
Column 'created_at' has 0 null value(s).
Column 'full_text' has 0 null value(s).
Column 'predicted_score' has 0 null value(s).
Column 'stock_ticker' has 0 null value(s).
Column 'num_stocks' has 0 null value(s).

(721740, 6)

In [78]:
# Load the Excel file into a DataFrame
df = pd.read_excel(r'C:\Users\Clover\Documents\kaggle_carina.xlsx')  # Replace 'your_file.xlsx' with the path to your file

# Extract the '57 Ticker' column as a list
stock_list = df['57 Ticker'].dropna().tolist()

print(stock_list)

def filter_by_stock(df, stock_list):
    """
    Filters a DataFrame to retain rows where stock_ticker contains 
    at least one stock from stock_list.

    Args:
    df (pd.DataFrame): The input DataFrame with a 'stock_ticker' column.
    stock_list (list): List of stock tickers to filter.

    Returns:
    pd.DataFrame: Filtered DataFrame.
    """
    # Ensure stock_ticker is a list (handling NaNs)
    return df[df['stock_ticker'].apply(lambda x: isinstance(x, list) and any(ticker in stock_list for ticker in x))]

# Example usage
# stock_list = ['GOOG', 'MSFT']
df_filtered = filter_by_stock(df_filtered, stock_list)

['TSLA', 'AAPL', 'AMZN', 'GOOGL', 'MSFT', 'META', 'F', 'NKE', 'NFLX', 'DIS', 'SBUX', 'WMT', 'INTC', 'PYPL', 'MCD', 'IBM', 'V', 'UPS', 'ORCL', 'BA', 'VZ', 'PEP', 'CSCO', 'ADBE', 'COST', 'CMCSA', 'KR', 'FDX', 'XOM', 'JPM', 'T', 'TMUS', 'MA', 'PFE', 'CVX', 'C', 'BAC', 'KO', 'WFC', 'GS', 'ES', 'HD', 'MS', 'PG', 'JNJ', 'UNH', 'AMD', 'NEM', 'CCL', 'TWTR', 'CAT', 'DOW', 'APD', 'AVGO', 'BK', 'EW', 'NVDA']

In [79]:
df_filtered.shape

(331384, 6)

In [80]:
df_filtered.head()

,id,created_at,full_text,predicted_score,stock_ticker,num_stocks
2,4,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,-1.062240,[MSFT],1
4,7,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,0.341477,[PFE],1
7,13,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,-0.530650,[AAPL],1
8,14,2020-04-09 23:56:51+00:00,$UMRX bouncing. EXTREMELY OVERSOLD #Coronaviru...,-1.029604,"[UMRX, DECN, OPGN, CODX, HTBX, TNXP, BA, APRN,...",40
11,19,2020-04-09 23:55:42+00:00,Treasury Secretary Mnuchin says US could be op...,0.209378,"[SPX, NDX, BIIB, MRNA, BNTX, AMZN, COST, WMT, ...",9

In [81]:
# Remove duplicate tweets in the 'tweet' column
df_filtered = df_filtered.drop_duplicates(subset=['full_text'], keep='first')

# Display the updated DataFrame
print(df_filtered.shape)

(3060, 6)

In [82]:
df_filtered

,id,created_at,full_text,predicted_score,stock_ticker,num_stocks
2,4,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,-1.062240,[MSFT],1
4,7,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,0.341477,[PFE],1
7,13,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,-0.530650,[AAPL],1
8,14,2020-04-09 23:56:51+00:00,$UMRX bouncing. EXTREMELY OVERSOLD #Coronaviru...,-1.029604,"[UMRX, DECN, OPGN, CODX, HTBX, TNXP, BA, APRN,...",40
11,19,2020-04-09 23:55:42+00:00,Treasury Secretary Mnuchin says US could be op...,0.209378,"[SPX, NDX, BIIB, MRNA, BNTX, AMZN, COST, WMT, ...",9
...,...,...,...,...,...,...
7828,10120,2020-04-09 11:36:50+00:00,I See A Slight Decline In The Daily US Death I...,-0.759455,"[AAPL, AMZN, AGN, BRK, BA, BHC, CRM, CMG, DIS,...",27
7838,10133,2020-04-09 11:35:37+00:00,$GOOG $GOOGL - Google ordered to pay French pu...,-0.045500,"[GOOG, GOOGL]",2
7839,10134,2020-04-09 11:35:33+00:00,Apple CEO to Take COVID-19 Questions at Virtua...,-0.071552,[AAPL],1
7842,10138,2020-04-09 11:35:06+00:00,$JPM to no longer offer loans to small busines...,-0.194720,[JPM],1
7844,10141,2020-04-09 11:34:49+00:00,RT @TheStreet: Amazon $AMZN is among the best-...,0.970295,[AMZN],1

In [83]:
def reduce_stock_ticker(df, stock_list):
    # Define a function to process each list in the 'stock_ticker' column
    def find_stock_match(ticker_list):
        # Iterate through the items in the list and return the first match
        for ticker in ticker_list:
            if ticker in stock_list:
                return ticker
        return None  # Return None if no match is found

    # Apply the function to the 'stock_ticker' column
    df['stock_ticker'] = df['stock_ticker'].apply(lambda x: find_stock_match(x) if isinstance(x, list) else None)

    return df

# Example usage:
# stock_list = ['GOOG', 'MSFT', 'AAPL', 'TSLA', 'AMZN']  # Example list of 57 stocks
# Assuming df is your DataFrame and 'stock_ticker' contains

In [84]:
df_filtered2 = reduce_stock_ticker(df_filtered, stock_list)

In [85]:
df_filtered2

,id,created_at,full_text,predicted_score,stock_ticker,num_stocks
2,4,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,-1.062240,MSFT,1
4,7,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,0.341477,PFE,1
7,13,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,-0.530650,AAPL,1
8,14,2020-04-09 23:56:51+00:00,$UMRX bouncing. EXTREMELY OVERSOLD #Coronaviru...,-1.029604,BA,40
11,19,2020-04-09 23:55:42+00:00,Treasury Secretary Mnuchin says US could be op...,0.209378,AMZN,9
...,...,...,...,...,...,...
7828,10120,2020-04-09 11:36:50+00:00,I See A Slight Decline In The Daily US Death I...,-0.759455,AAPL,27
7838,10133,2020-04-09 11:35:37+00:00,$GOOG $GOOGL - Google ordered to pay French pu...,-0.045500,GOOGL,2
7839,10134,2020-04-09 11:35:33+00:00,Apple CEO to Take COVID-19 Questions at Virtua...,-0.071552,AAPL,1
7842,10138,2020-04-09 11:35:06+00:00,$JPM to no longer offer loans to small busines...,-0.194720,JPM,1
7844,10141,2020-04-09 11:34:49+00:00,RT @TheStreet: Amazon $AMZN is among the best-...,0.970295,AMZN,1

In [86]:
# Drop the 'num_stocks' column from the DataFrame
df_filtered = df_filtered.drop(columns=["num_stocks"])

# Display the updated DataFrame
df_filtered.head()

,id,created_at,full_text,predicted_score,stock_ticker
2,4,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,-1.062240,MSFT
4,7,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,0.341477,PFE
7,13,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,-0.530650,AAPL
8,14,2020-04-09 23:56:51+00:00,$UMRX bouncing. EXTREMELY OVERSOLD #Coronaviru...,-1.029604,BA
11,19,2020-04-09 23:55:42+00:00,Treasury Secretary Mnuchin says US could be op...,0.209378,AMZN